name: WebRTC xcframework builds
on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
      - '.gitignore'
      - '.dockerignore'
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      commitHash:
        description: 'webrtc-sdk commit hash'
        default: ''
        required: true
      configuration:
        description: 'build configuration'
        default: 'release'
        required: true
        type: choice
        options:
          - release
          - debug

permissions:
  packages: write
  contents: write
  actions: read

jobs:
  build-apple:
    strategy:
      fail-fast: false
    name: Build webrtc xcframework for apple
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Select Xcode 26.0
        run: sudo xcode-select --switch /Applications/Xcode_26.0.app/Contents/Developer

      - uses: actions/setup-python@v4
      - run: pip3 install setuptools

      - name: Install macos dependencies
        run: brew install ninja

      - name: Print ninja version
        run: ninja --version

      - name: Target OS
        run: echo -e "\ntarget_os = [\"mac\",\"ios\",]" >> .gclient
        shell: bash
        working-directory: build
        
      - name: Build WebRTC
        run: chmod +x ./xcframework_dynamic_build.sh && ./xcframework_dynamic_build.sh release
        working-directory: build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: webrtc-xcframework
          path: build/out-release/WebRTC.xcframework.zip*

  create-release:
    name: Release to GH (Draft)
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - build-apple
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: webrtc-xcframework
          path: ${{ github.workspace }}/webrtc-xcframework
    
      - name: Create draft release
        run: |
          gh release create ${{ github.ref_name }} --draft --title "${{ github.ref_name }}"
          gh release upload ${{ github.ref_name }} ${{ github.workspace }}/webrtc-xcframework/*
