name: LibWebRTC binary compilation/deployment.
on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
      - '.gitignore'
      - '.dockerignore'
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      commitHash:
        description: 'webrtc-sdk commit hash'
        default: ''
      configuration:
        description: 'build configuration'
        default: 'release'
        required: true
        type: choice
        options:
          - release
          - debug

permissions:
  packages: write
  contents: write
  actions: read

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, arm64]
        profile:
          - ${{ github.event.inputs.configuration || 'release' }}
    name: Build libwebrtc.so for linux (${{ matrix.arch }}-${{ matrix.profile }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: install setuptools
        run: |
          pip3 install setuptools # pkg_resources is sometimes not found?

      - name: Install linux dependencies
        run: |
            sudo apt update -y
            sudo apt install -y ninja-build pkg-config openjdk-11-jdk

      - name: Print ninja version
        run: ninja --version

      - name: Target OS
        run: echo -e "\ntarget_os = [\"linux\"]" >> .gclient
        shell: bash
        working-directory: build

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          android: false
          tool-cache: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Build WebRTC
        run: chmod +x ./libwebrtc_linux_build.sh && ./libwebrtc_linux_build.sh --arch ${{ matrix.arch }} --profile ${{ matrix.profile }}
        working-directory: build

      - name: Zip artifact (Unix)
        run: |
          cd build
          zip ${{ github.workspace }}/libwebrtc-linux-${{ matrix.arch }}-${{ matrix.profile }}.zip linux-${{ matrix.arch }}-${{ matrix.profile }} -r

      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: libwebrtc-linux-${{ matrix.arch }}-${{ matrix.profile }}
          path: libwebrtc-linux-${{ matrix.arch }}-${{ matrix.profile }}.zip

  build-win:
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, arm64]
        profile:
          - ${{ github.event.inputs.configuration || 'release' }}
    name: Build libwebrtc.dll for windows (${{ matrix.arch }}-${{ matrix.profile }})
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install windows dependencies
        run: |
          Invoke-WebRequest -Uri "https://github.com/ninja-build/ninja/releases/latest/download/ninja-win.zip" -OutFile ninja.zip
          Expand-Archive -Path ninja.zip -DestinationPath ${{ github.workspace }}\ninja
          echo "${{ github.workspace }}\ninja" | Out-File -Append -Encoding utf8 -FilePath $Env:GITHUB_PATH

      - name: Print ninja version
        run: ninja --version

      - name: Target OS
        run: echo -e "\ntarget_os = [\"win\"]" >> .gclient
        shell: bash
        working-directory: build

      - name: Build WebRTC
        run: .\libwebrtc_win_build.cmd --arch ${{ matrix.arch }} --profile ${{ matrix.profile }}
        working-directory: build

      - name: Zip artifact (Windows)
        run: Compress-Archive -Path .\build\libwebrtc-${{ matrix.arch }}-${{ matrix.profile }} -DestinationPath .\build\libwebrtc-win-${{ matrix.arch }}-${{ matrix.profile }}.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: libwebrtc-win-${{ matrix.arch }}-${{ matrix.profile }}
          path: build\libwebrtc-win-${{ matrix.arch }}-${{ matrix.profile }}.zip

  build-apple:
    strategy:
      fail-fast: false
    name: Build webrtc xcframework for apple
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Select Xcode 26.0
        run: sudo xcode-select --switch /Applications/Xcode_26.0.app/Contents/Developer

      - name: Print ninja version
        run: ninja --version

      - name: Target OS
        run: echo -e "\ntarget_os = [\"mac\",\"ios\",]" >> .gclient
        shell: bash
        working-directory: build
        
      - name: Build WebRTC
        run: chmod +x ./xcframework_dynamic_build.sh && ./xcframework_dynamic_build.sh release
        working-directory: build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webrtc-xcframework
          path: build/out-release/WebRTC.xcframework.zip*

  create-release:
    name: Release to GH (Draft)
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - build-apple
      - build-win
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: webrtc-xcframework
          path: ${{ github.workspace }}/webrtc-xcframework
    
      - name: Create draft release
        run: |
          gh release create ${{ github.ref_name }} --draft --title "${{ github.ref_name }}"
          gh release upload ${{ github.ref_name }} ${{ github.workspace }}/webrtc-xcframework/*
